// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesHolland.Models;

namespace RazorPagesHolland.Migrations
{
    [DbContext(typeof(RazorPagesHollandContext))]
    partial class RazorPagesHollandContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RazorPagesHolland.Models.Holland", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DiveDate");

                    b.Property<float>("Latitude")
                        .HasColumnType("float(10, 6)");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<float>("Longitude")
                        .HasColumnType("float(10, 6)");

                    b.Property<string>("ROVDiveName")
                        .IsRequired();

                    b.Property<string>("VesselName")
                        .IsRequired();

                    b.Property<string>("VideoUrl")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Holland");
                });

            modelBuilder.Entity("RazorPagesHolland.Models.Survey", b =>
                {
                    b.Property<int>("SurveyID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HollandID");

                    b.Property<float>("Latitude")
                        .HasColumnType("float(10, 6)");

                    b.Property<float>("Longitude")
                        .HasColumnType("float(10, 6)");

                    b.Property<DateTime>("TimeInterval");

                    b.Property<int>("VesselNumber");

                    b.HasKey("SurveyID");

                    b.HasIndex("HollandID");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("RazorPagesHolland.Models.Survey", b =>
                {
                    b.HasOne("RazorPagesHolland.Models.Holland", "Holland")
                        .WithMany("Surveys")
                        .HasForeignKey("HollandID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
